### ISSUE TITLE
Code for D2RL algorithm

### ISSUE THREAD

**Issue by zincopper** [michigan-traffic-lab/Dense-Deep-Reinforcement-Learning#1]
Would you happen to provide the source code for the D2RL algorithm publicly? I have only been able to find the trained parameters in checkpoints. It would be greatly appreciated if the source code for the algorithm could be provided. Thank you.

**Comment by Wi11ione** [comment]
Currently there is no "DRL_gym_ENV_offline" method provided for generating training environments in the training part of D2RL. If you could provide the code for the D2RL training environment, I would greatly appreciate it!

**Comment by Zoe-Wan** [comment]
Hello! Your work is very interesting and I wonder if you can publish the detail of the training part? I 'm reproducing your work and I really need it!!

**Comment by Zoe-Wan** [comment]
> Would you happen to provide the source code for the D2RL algorithm publicly? I have only been able to find the trained parameters in checkpoints. It would be greatly appreciated if the source code for the algorithm could be provided. Thank you.

I notice that the training part of NADE can be found in the repo https://github.com/michigan-traffic-lab/Naturalistic-and-Adversarial-Driving-Environment.git . That may be useful, but I still wonder the differences of these two researches. According to the paper, I think the differences in the training part is very important (One updates the parameters in every step, and another only updates them in critical step). I think this training part should be published. Thanks!

**Comment by miracelplus** [comment]
Hi all,

The code for D2RL training algorithm has been uploaded to this repo. Please refer to README_D2RL_Train.md for detailed guidance.

Best,

Haowei

**Comment by hugeshark7** [comment]
Hi Haowei,
when i follow the instruction runing the D2RL_train.py, it shows no module of RLlib.agents. I do see the initial file, but i have no idea how to register an agent. By the way, can I modify the maps file to train other agents using this D2RL_train.py. I would really appreciate your reply!
