### ISSUE TITLE
What kind of computer can reproduce the results of this paper?

### ISSUE THREAD

**Issue by MoMingQimio** [michigan-traffic-lab/Dense-Deep-Reinforcement-Learning#2]
I am a PhD-to-be in the field of automatic driving and I need to configure a computer for my research, how do I choose a graphics card?

**Comment by miracelplus** [comment]
Hi,

To reproduce the result, dedicated graphic card is not required. However, if you would like to run the testing experiments yourself, I will suggest using clusters.
